### ISSUE TITLE
Feature Request: Progress Indicator

### ISSUE THREAD

**Issue by FiZiX** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#1]
Hey, love the work you've done so far! I just wanted to enter a small feature request:

Would it be possible to add some sort of progress indicator while the build_pack and parse_pack scripts are running? Maybe something counting the number of ROMs processed or a percent complete indicator?

Keep up the good work!

**Comment by frederic-mahe** [comment]
Hi @FiZiX ,

I've added to `parse_pack.py` what seems to be the simplest form of progress indicator in python 3 (see commit https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commit/5309993c2149de248ffe6ea4f9b77f6c443b7211). I aim for simplicity because I would like the scripts to work on a wide spectrum of systems. The progress report works on Linux and Windows 7, but the fast refresh makes the screen flicker on Windows (at least on my test machine).

Can you please confirm it works for you? If yes, I'll do the same for the `build_pack.py` script.

**Comment by FiZiX** [comment]
Thanks! I'll try it out this weekend and report the results.

**Comment by FiZiX** [comment]
Works perfectly on Windows 10!

**Comment by frederic-mahe** [comment]
The same code is now in the `build_pack.py` script. It works as expected on Linux, and it should work on Windows too.

**Comment by FiZiX** [comment]
I finally got to test the build_pack script last night and it also worked perfectly on Windows 10. Thanks again!
