### ISSUE TITLE
SNES: copy of Test Drive II does not match nointro and may be bad dump

### ISSUE THREAD

**Issue by tjanas** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#125]
I cannot find a match for this entry:
```
6b5469111174f313897adefa579c3ad249175dea3b3940ec86c107d6ee2f87cd	SD2SNES/1 US - T-Z/Test Drive II - The Duel (U) (24291).smc	754f30e9d06c304d4938af79d1a4f4999a2d60e0	ef76f860cd8709daf99a60e9dac8d2be	ba093e24
```

The following entry does match [no-intro](https://datomatic.no-intro.org/?page=show_record&s=49&n=0675):

```
c9563cb57314588aa3db22b76dc8acfba3e73733dd3538edd90af5a15595830e	SD2SNES/1 US - A-E/Duel, The - Test Drive II (USA).sfc	038bac2a85d323c6e1950344d6bbc86c6173e293	55a4acec09123b39949d2affb9f7c7c2	1cc662cd
```

**Comment by tjanas** [comment]
@frederic-mahe if @SmokeMonsterPacks is retired from this project, I would be happy to pick up the torch and keep it going.

**Comment by frederic-mahe** [comment]
fixed in 5f62438d9a9df66abdb76b308ac84983157a62cb

**Comment by frederic-mahe** [comment]
> @frederic-mahe if @SmokeMonsterPacks is retired from this project, I would be happy to pick up the torch and keep it going.

@tjanas are you still willing to maintain packs? is there a pack you would like to focus on? I can write custom scripts to detect certain issues if that helps.

**Comment by tjanas** [comment]
Sure, I'd still like to help maintain packs. I'd like to focus on Everdrive N8, SD2SNES, NT Jailbreak, especially since I have some of the hardware for those (I own an NT Mini, an original N8, and SD2SNES, but not a PowerPack, N8 Pro, or Super Everdrive).

**Comment by frederic-mahe** [comment]
thanks @tjanas ! I am done modifying the packs for today. I have scripts that can help us detect more discrepancies and errors, but first I've been trying to close as many issues as possible. If you are interested, there are two linked issues you could help me solve: #80 and #116

It requires some detective work to find the true `Taekwon-Do (Korea)`.

Beyond that, issue #38 contains a list of N8 or SD2SNES things that could be improved, or were already fixed by SmokeMonster, I am not sure. Ideally, we should split issue #38 into several, more focused independent issues.

**Comment by tjanas** [comment]
@frederic-mahe Please see [my findings](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/issues/116#issuecomment-610467177) on Taekwon-Do (Korea).
