### ISSUE TITLE
Feature Request: Symlinking of duplicate roms/files

### ISSUE THREAD

**Issue by amoore2600** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#127]
There is a need to add an option for the symlinking of duplicate files in the build_pack.py

**Case:** During the curation of a rom pack, often the same file is used in multiple places in the pack.

**Future Resolve:** Rather than have the original file duplicated, the additional matching files that have the same check sum when building a pack should be symlinked to the original file. This action should only be invoked by a switch in the command options and should not be the default.  

This option will grow more important as disk based curation grows.

**Comment by frederic-mahe** [comment]
Hi @amoore2600 

there is a `--file_strategy hardlink` option. Maybe that would suit your need? There is a nuance between hardlinks and symlinks, and I think hardlinks are better suited for file hierarchies with a lot of duplication.

> Options for advanced users:

> --file_strategy {copy,hardlink} changes the way files are copied to the destination folder. The default is to physically duplicate the files (copy). The option hardlink avoids file duplication and saves storage space for pack builders. Please note that when copying to a FAT32 SD card, hardlinks are automatically converted into normal files.

**Comment by Slashbunny** [comment]
The problem with the current implementation is that your source ROMs folder and the destination need to be on the same file system for hardlinks to work (which is not a limitation of symlinks).

Typically, these packs are used where the source ROMs folder is on a harddrive on a PC somewhere and the destination is a SD card.  I imagine with disk images, the SD card is replaced with an external harddrive, which means the current implementation won't work with the way people normally use the scripts. 

A possible workaround is to put a `_roms/` folder on your external harddrive with all your source roms, then run:

`build_pack.py -i /usbhdd/_roms/ -d TheRomList.SMDB -o /usbhdd/ --file_strategy hardlink`

You must do the hardlinking on the destination filesystem, you can't do this on another filesystem and move everything over (it'll just make copies). Also, exFAT doesn't support hardlinks or symlinks so it'd need to be NTFS or *nix filesystem. 

I haven't personally tried this workaround, but it _should_ work, it's just not ideal. 

If you wanted better "native" support for something like this, `./build-pack.py` would need to copy the file into the destination folder **once**, then each time the script encounters the same file hash, it'd make a symlink/hardlink to the first file copied. If it works the way it's supposed to, it could be the default behavior if the destination system supports linking. If it's exFAT (like a SD card), it'll behave as it does today and copy everything. 

Symlinks and hardlinks are fundamentally different technically speaking, but the technical differences are not important in this use case, IMO. 

For example, my MiSTer setup is entirely on a network share and everything is symlinked into the MiSTer folder structure so it's obvious to me where the "source" of everything is elsewhere on the server. Hardlinks would technically work just fine too, but it would be more difficult to ascertain whether or not I copied something into the destination by mistake, if the file was a non-smpack file, or it is an "expendable" hardlink that can be removed. hardlinks are indistinguishable from normal files because they _are_ normal files. 

I think either option is pretty viable (or support both), the challenge is the "copy once and link afterwards" logic.

**Comment by amoore2600** [comment]
Wonder if something could make a soft link that is just a file on the creating system but when is transferred to something like MiSTer works correctly. The correct path could be in the db.txt.

**Comment by frederic-mahe** [comment]
Sorry guys, I use the hardlink feature to build and maintain pack faster (no file copy). I've never tried to symlink things from my MiSTer to a NAS or a USB drive, so I am not 100% sure to get your setups.

To summarize what I understand, you would like to build a pack were only the first occurrence of a file is real, all other occurrences are symbolic links (small files with the address of the first file), in the target filesystem (if different from the filesystem containing the source ROMs.

I think it can be scripted fairly easily post-facto, once you have a pack of ROMs and the SMDB file that what used to build it. With the SMDB file, you know were the duplicates are and you can replace them with local symlinks to the first file occurrence. However, this is not something I can bake into the `build_pack.py` script in the foreseeable future. I am too busy with work and other projects. SMDB files have received a lot of updates and improvement lately, and I'd prefer to use my time helping with that. 

Also, there is almost no duplication in the main folders of a pack. Almost all duplicates are in the _Game Series Collections_. If storage space is really scarce, and if hardlinks don't work for you, why not drop that folder?

> hardlinks are indistinguishable from normal files because they are normal files.
There are ways to find them:
```sh
find . -type f -links +1
```

**Comment by Drakonas** [comment]
The issue with symlinking of duplicate files/roms on Windows systems is that Windows' file manager will not copy them properly a lot of times to another drive. Fat32 does not support hard or softlinks as well, which is usually the target filesystem for these packs since that's the defacto filesystem type that flashcarts support.

**Comment by frederic-mahe** [comment]
> To summarize what I understand, you would like to build a pack were only the first occurrence of a file is real, all other occurrences are symbolic links (small files with the address of the first file), in the target filesystem (if different from the filesystem containing the source ROMs.

Here is a shell script that will replace all duplicates with symlinks:
```sh
SMDB="./path/to/SMDBs/EverDrive N8 & PowerPak SMDB.txt"
FIRST_HASH=""
SOURCE=""

# assuming we are at the root of the folder we want to deduplicate
sort -k1,1d -k2,2d "${SMDB}" | \
    cut -f 1,2 | \
    while read HASH FILENAME ; do
        if [[ ${FIRST_HASH} != ${HASH} ]] ; then
            FIRST_HASH="${HASH}"
            SOURCE="${FILENAME}"
            continue
        else
            ln --force --symbolic --relative "./${SOURCE}" "./${FILENAME}"
        fi
    done
```
it takes only a few seconds to run on a NES pack.

I am going to close this issue now, feel free to re-open or start a new issue if need be.
