### ISSUE TITLE
Ultracore, Xeno Crisis in Mega EverDrive SMDB

### ISSUE THREAD

**Issue by tjanas** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#172]
I don't think it is appropriate to include recent releases that are still being sold.

This entry should be removed as the cart is [still available for sale](https://www.play-asia.com/ultracore/13/70cuzj), and the naming syntax is also incorrect (also this is a different version than the one on the Mega Sg):
`Ultracore (MJ-1.0) - 1995 Dice - 2019 Columbus Circle - Mega SG Bundled.md`

This entry should also be removed, [the ROM is still for sale](https://shop.bitmapbureau.com/collections/sega-mega-drive-genesis/products/xeno-crisis-sega-mega-drive-genesis-rom-download):
`Xeno Crisis.md`

**Comment by maniac79** [comment]
There are only hashes in the packs, I think it may even lead to people getting aware of these games' existence and going out to buy them.

I only joined this project very recently because I happen to have some free time atm and I'm not 100% sure but I believe including such games is in line with SmokeMonster's vision, he also had included hashes for games which are commercially available (e.g. Micro Mages on NES).

**Comment by tjanas** [comment]
@maniac79 you make a good point with Micro Mages; if it was added by @SmokeMonsterPacks, then maybe it is ok to keep entries like this?

**Comment by FiZiX** [comment]
Nobody asked for my opinion but here it is: I think it's fine to include hashes for games like Xenocrisis and Tanglewood because the developers made the ROMs available to backers. For example, I backed Xenocrisis and received a ROM which was meant to be played on a flash cartridge. I would love to have that ROM as part of my SmokeMonster pack without having to edit the SMDB file every time a new version of the file is released.

**Comment by frederic-mahe** [comment]
@FiZiX this is a community-driven project, everyone can chime in.

I too think it makes sense to include these entries: practicality, awareness, publicity, completeness. Since packs are only hash lists, there is no harm done to developers I think. We could even check with some of them if they'd be ok with that. Maybe the Tanglewood dev has a twitter account?

Of course, if an entry is wrong or outdated it should be fixed or removed.

**Comment by frederic-mahe** [comment]
I am going to close that issue then.

**Comment by SmokeMonsterPacks** [comment]
These absolutely will not be included or this entire project will be shut down. No discussion, active indie is NOT to be included. Did some make its way into the SMDBs? If so, I will pull them all offline until they are removed.

**Comment by tjanas** [comment]
@SmokeMonsterPacks I can submit a pull request to remove the ones I discovered.

**Comment by frederic-mahe** [comment]
@tjanas I've just pushed a new `Mega` without indie entries (except the public demo for Tanglewood). Can you please deal with the other files?

**Comment by SmokeMonsterPacks** [comment]
Thanks, I took it offline. Please let me know if any other packs need to come down in the meantime too while these get cleaned out.

**Comment by SmokeMonsterPacks** [comment]
Oops, simulposted with you there. Thanks for fixing that so quickly @frederic-mahe :D

**Comment by tjanas** [comment]
Please review https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/pull/177

**Comment by tjanas** [comment]
Please review https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/pull/178

**Comment by frederic-mahe** [comment]
ok, all entries regarding active indie studios were removed.

Regarding _Tanglewood_, I contacted the dev earlier this morning and he is fine with having his game listed in SMDBs. If I remember correctly the interview he gave to Bob from RetroRGB, the plan is to make _Tanglewood_'s code public in the near future. When that will be the case, we will include that game again in our databases.

**Comment by tjanas** [comment]
I believe the source to Tanglewood is already available? https://github.com/BigEvilCorporation/TANGLEWOOD

**Comment by frederic-mahe** [comment]
Oh, I didn't know that. I am not sure what to do then? The source was made public, but compiling it requires skills and proprietary software.
