### ISSUE TITLE
N64: replace all byte-swapped or little-endian entries with big-endian

### ISSUE THREAD

**Issue by frederic-mahe** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#199]
As of now, we have 298 `.n64` entries (little-endian) and 2405 `.z64` entries (big-endian). Some `.n64` are in fact `.v64` (byte-swapped).

@tjanas wrote:
> https://en.m.wikipedia.org/wiki/List_of_Nintendo_64_ROM_file_formats

> https://www.reddit.com/r/emulation/comments/7hrvzp/the_three_different_n64_rom_formats_explained_for/?utm_source=amp&utm_medium=&utm_content=post_body

> I think Everdrive 64 supports Big Endian and it is also the format used by no-intro. Technically, that seems to be represented with a .z64 file extension.

> https://datomatic.no-intro.org/?page=show_record&s=24&n=0717

We should aim for one format only, big-endian.

**Comment by tjanas** [comment]
I'll work on this.

**Comment by tjanas** [comment]
Drakonas may be doing N64 work, including this, so I will refrain from making changes to this.

**Comment by Drakonas** [comment]
I already have every rom in proper Big-Endian format from a confirmed source. I can pull the latest version, rebuild the listing from SMDB and then submit a pull request with the switched roms. However I wonder if I should do the small changes first before doing a large commit like that.

**Comment by tjanas** [comment]
Let’s not do the Endian change until all other issues are worked out.

**Comment by amangiat** [comment]
> I already have every rom in proper Big-Endian format from a confirmed source. I can pull the latest version, rebuild the listing from SMDB and then submit a pull request with the switched roms. However I wonder if I should do the small changes first before doing a large commit like that.
> 
> Let me know what you think..

@Drakonas 
would it be possible to make a branch with the big endian changes? i would really like a pack that works with the no-intro set?

**Comment by tjanas** [comment]
What small outstanding issues are there with N64? If there aren’t any, maybe it is time to proceed with the BigEndian changes?

**Comment by Drakonas** [comment]
Well, the main thing is the question of replacing all Game Series Collection roms with the latest revision of each game. Most of the Game Series Collection entries have the 1.0 versions. I feel if people are using Game Collections, they aren't attempting to practice speedrunning (which would be illegal with a flashcart anyway, I think), so I figure having the latest revisions of the games would be ideal since they tend to be the most bug-free.

The other thing is completing the Chronological folder. I have all this complete on my end but I'd have to put in a pull request. But I'm still waiting on if we want to split that off to a separate pack or not.

**Comment by tjanas** [comment]
As part of this change, I would recommend not adding new hacks. I think we will still maintain one SMDB and not make GSC its own SMDB (although GSC should not contain any entries not found in the main directories).

**Comment by Drakonas** [comment]
Sure thing @tjanas. I just know the idea had been tossed around to split the Chronological folders out because they're going to be just as huge as the main US folder, and not many people use them. In any case, I can push the Chronological pull request and then I just need to know if we want to replace all GSC titles with their latest revisions if they have multiples, and also I wonder if we want to add iQue Player games (probably not, but I thought I'd ask).

**Comment by tjanas** [comment]
As a first phase, what if we leave GSC alone and just update the main folders? That can be checked against a bigendian no-intro dat. Then a different pull request can handle updating GSC (for BigEndian, chronological fixes, making sure GSC uses latest revisions, etc).

**Comment by Drakonas** [comment]
@tjanas I can work on getting everything switched over to No-Intro proper dumps for the main folders and send a pull request if you'd rather do that first. But I'd also like to hear tjstogy's thoughts on the matter before I start undergoing that task. I have it updated on my end with a separate pack, but getting it in-line with the current smdb would require a little more work, since I was mainly working with a customized folder layout with my WIP folder.

**Comment by tjanas** [comment]
I am going to go ahead and fix this shortly.
