### ISSUE TITLE
Idea/proposal: create separate GB and GBC SMDBs

### ISSUE THREAD

**Issue by tjanas** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#477]
The EverDrive GB could have two placeholder directories where these packs are dropped in. These separate GB and GBC could also be used as drop-ins for Noir and Nt Mini Legacy SMDB placeholder directories.

A standalone GB smdb would contain only GB and GB-compatible GBC files.

A standalone GBC smdb would contain only GBC files.

No-intro maintains two dats for GB and GBC.

Thoughts?

**Comment by steve1515** [comment]
Since the EverDrive GB pack only consists of GB and GBC files does that mean that it would basically just become an SMDB with empty files?

I'm not sure how this work work with the SGB Enhanced Game Series, etc. directories where there is a mix of GB and GBC files. It may make it difficult to create an EverDrive GB pack if they are broken out and would not be a simple drop in from the two new SMDBs. (Maybe I'm not understanding correctly though?)

**Comment by tjanas** [comment]
Yes, essentially it would be an empty pack. The specific mixed Enhanced Game Series would go away. Take a look at how I broke up GB and GBC in the new Nt Mini Noir smdb.

**Comment by tjanas** [comment]
Or, this EverDrive GB pack could still have that Enhanced Game Series directory, and the main GB and GBC directories would be drop-ins.

**Comment by tjanas** [comment]
I feel that Game Series Collections should generally be their own standalone SMDBs too, as they are more subjective anyways.

**Comment by steve1515** [comment]
I see what you're saying. The EverDrive GB would become 2 empty directories.

The only thing that I don't see is that the "3 GB with GBC Color Palettes" directory is missing from your Nt Noir SMDB. That should not be removed from the GBC packs if separated.

I could see the Game Series Collections being separated/half & half with the GB and GBC packs so that they each have a Game Series Collections directories with only .gb or .gbc files. (if they don't get broken out to entirely separate SMDBs)

**Comment by tjanas** [comment]
Yeah, that GB with GBC Color Palettes directory can still remain in the EverDrive GB smdb.

**Comment by steve1515** [comment]
I think the GB with GBC Color Palettes directory could be removed from the EverDrive GB smdb and put in the new GB smdb only. Wouldn't that further organize it? This way we can make it so that the EverDrive GB smdb really is only 2 empty files in 2 directories.

**Comment by tjanas** [comment]
I agree. In my GB organization in the Noir smdb, I think there is a GB-compatible GBC (I forgot the exact name) directory that essentially has the same coverage.

**Comment by tjanas** [comment]
I am not sure how to validate everything that should be within `3 GB with GBC Color Palettes/`. Is there a definitive list somewhere? I don't think rom hacks/translations or bad dumps should be contained in this directory either.

**Comment by steve1515** [comment]
Would this work? https://tcrf.net/Notes:Game_Boy_Color_Bootstrap_ROM

**Comment by tjanas** [comment]
This a list of palettes but not games.

**Comment by steve1515** [comment]
If you go down to the "Assigned Palette Configurations" is lists the games in the table for the pallets they belong to.
