### ISSUE TITLE
Feature request: copy files not in the database to a particular folder

### ISSUE THREAD

**Issue by re4mat** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#505]
At present, it's very tedious to go through the "missing" file after building to determine which files were not found in the database and thus not copied over. The behaviour seems to be that it just leaves those files alone. Instead, it would be very nice if those files were copied into an "/unprocessed" or "/notfound" or whatever directory so that you could have all the unprocessed files in one place.

**Comment by steve1515** [comment]
I may be misunderstanding, but the missing file generated from the build_pack script lists out files that are in the SMDB but that you don't have in your source folder. These "missing" files do not exist, so they cannot be moved into any folder. It's basically letting you know what you need those files to make a complete pack according to the SMDB.

**Comment by tjanas** [comment]
@steve1515 is 100% correct.

**Comment by re4mat** [comment]
That's not what I mean. Say you have a ROM in your source folder that's not in the database, but you want to have it in your processed pack. Since it's not in the database, the script will ignore it and not do anything with it. It will remain in your source folder. My NES source folder, for example, is a flat folder containing currently 2770 ROMs. Finding which files in that source folder were not moved because they weren't in the database is currently a pain. If instead those files which were not found in the database were copied to a separate folder, it would be much easier to see which files were not sorted into the pack, so that I could then move it manually.

**Comment by steve1515** [comment]
I don't think that feature should be added to the build_pack script as it would be out side the scope of that script. But, in your case, since you have a flat source directory, you could simply execute a command to do the work for you. For example, on the Windows command line you could use the a command similar to the following.
`for /f "tokens=1" %a in (missing.txt) do ( move %a extra\%a )`
This command would move all the files listed in the missing.txt file to the 'extra' subdirectory within your source directory. (Note: You would need to adjust the path to missing.txt and the subdirectory as needed.)
