### ISSUE TITLE
How to just verify pack, not add/replace/rename/move/remove roms

### ISSUE THREAD

**Issue by elmimmo** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#7]
Neither the README nor the wiki document how to simply audit a pack, that is, simply verify whether the pack has missing roms, roms with unknown hash (i.e. same filename+location but different hash) and/or foreign files (i.e. files with filename+location not listed in in the SMDBs).

**Comment by kraqh3d** [comment]
I produced an audit_pack.py script that does this. I plan to submit it as a pull request after I tweak it some more. It traverses the SD2SNES folder reporting the correct hashes (path and hash match the database), incorrect hashes (path matches but hash does not database), foreign hashes (hash does not exist in database), and files in the wrong location.  The wrong location is kind of funny though because the same file exist in more than one path so it dumps all possible paths.

**Comment by frederic-mahe** [comment]
Hi @elmimmo 

I've added that to the wiki:

**auditing** to check what is missing or extra in a ROM pack, the simplest way is to call `parse_pack.py` onto the pack to produce a text file, and then to compare that text file with the corresponding `SMDB` file. Comparing two text files is a very basic operation that can be performed by many tools, starting with the `diff` command on Unix/Linux and the diff-like graphical tools on Windows. 

@kraqh3d Of course a script could do the job more specifically.
