### ISSUE TITLE
MiSTer pack has invalid/problematic characters

### ISSUE THREAD

**Issue by coughlanio** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#90]
MiSTer pack has the following files which contain problematic characters:

```
MiSTer/Amstrad/Games [CDT] Tapes Non-TOSEC/jetski - FÆRDIG.cdt
MiSTer/Amstrad/Games [CDT] Tapes Non-TOSEC/jetski2 - FÆRDIG.cdt
MiSTer/Amstrad/Games [DSK] Non-TOSEC/A Toda Máquina (S) (-) (Disk 1of 2).dsk
MiSTer/Amstrad/Games [DSK] Non-TOSEC/A Toda Máquina (S) (-) (Disk 2 of 2).dsk
MiSTer/Amstrad/Games [DSK] Non-TOSEC/Capitán Trueno.dsk
```
This appears to cause issues with the pack building, as built out packs exclude these files.

**Comment by magardner111** [comment]
Temporary fix: Python assumes it's UTF-8 but it's Latin ISO-8859-1.

in your "with open" on line 122, add the argument encoding="ISO-8859-1"

**Comment by frederic-mahe** [comment]
It seems SmokeMonster fixed the problem upstream by replacing non-ascii characters with ascii-proxy in all the concerned filenames. Therefore, I'll close that issue.

For future reference, I think a way to solve the problem is to reencode characters when creating the SMDB files, i.e. when **parsing** the file system. Assuming it is done on a computer running Windows, filenames should be encoded in UTF-16. Python code could be something like  `.decode("utf-16")` to read file names and paths, and  `.encode("utf-8")` to write them to a file (UTF-8 seems to be the universal encoding). When building the packs, the python script would then be guaranteed to read filename and paths encoded in UTF-8.
