### ISSUE TITLE
Add `--file_strategy move`

### ISSUE THREAD

**Issue by elmimmo** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#95]
Add the ability to move files when building a pack, so that only unregonized ROMs remain. As of now, there is no way AFAK to know what ROMs in the source folder are not in the SMDB.

**Comment by fartwhif** [comment]
hey there, good idea, I've added a TO-DO related to unknown files to my project [here](https://github.com/fartwhif/GammaCopy/issues/1)

**Comment by dgubitosi** [comment]
I've thought about this.  The problem with move is that there are a ton of duplicate files.

**Comment by elmimmo** [comment]
True. Well, then, the motive for this feature request, as stated in the issue description is actually getting to know what files are unknown, so still getting that list output to either stdout or a text file is something that would be nice to have. I will add a new issue explicitly requesting that. Feel free to close this issue.

**Comment by dgubitosi** [comment]
My experiments with move were so that I could bring already built folders up to date with changes to the SMDB.  But now I see that this could work.  When a source file matches, move and copy it to all the duplicates in the collections directory.  Here's where things got funny for me.  This leaves the old collections folder lingering since it no longer matches based off the current logic in build_pack.  The way to address this is to maintain another list of all the hashes that were already matched.  The source files could be additionally compared to this list and then deleted if a match is found as they would be duplicates.  What would then be left are the files that don't match the hashes in the SMDB.  Does that sound about right?

So now I'm curious what would you do with the list of leftover / non-matching files?  There can be a ton of files that don't match an SMDB.  For example, point build_pack at a Goodset or a TOSEC source folder.  They are full of various bad dumps and hacks.   

Regarding logging, I recently added an audit log option but didn't do a pull request yet.  I write two longs during build_pack.  A "match.log" file contains the sha256 hash and filename of the files that match (using their SMDB path and filename, not the source path and filename).  And a "missing.log" file contains the sha256 hash and filename of the files in the SMDB that could not be matched.  It should be easy to add source.log showing all the scanned source files and what happened to them, such as:
(1) hash match so it was moved/copied to the destination location,  (2) duplicate hash so it was ignored or deleted depending on the strategy, or (3) unknown hash which was ignored.

What do you think?

**Comment by frederic-mahe** [comment]
Hi, I tend to favor good old text manipulation shell tools for that kind of work, rather than adding options to the script.

Since we already have a list of desired files (the "target SMDB"), we can use the `parse_pack.py` script to parse the files we have (`fake SMDB`) and compare the two lists (`target SMDB` vs. `fake SMDB`). It is then easy to perform a set operation (exclusion) with the `comm` command to obtain a list of files that **are not** in the `target SMDB`:
```sh
TARGET_SMDB="Vectrex SMDB.txt"
FAKE_SMDB="tmp.smdb"
python3 parse_pack.py --folder ./fake/ --output "${FAKE_SMDB}"
comm -23 \
     <(cut -f 1 "${FAKE_SMDB}" | sort -du) \
     <(cut -f 1 "${TARGET_SMDB}"| sort -du) | \
    grep -F -f - "${FAKE_SMDB}"

rm -f "${FAKE_SMDB}"
```
The obtained list of files can then be further used for deletion, extraction, or any other action.

That being said, I am not sure what you would like to do with the files that are not in the SMDB. My personal pipeline is usually as follows: grab a Goodset, a NoIntro set and an older version of the pack; decompress everything in a tmp folder; build the new pack; erase the tmp folder. That's it. Eventually, I'll have a look at the "missing file" to check if I'm missing something important or cool.

I never had to look at what is not in the SMDB. That could be a way to identify holes in SmokeMonsters curated sets, but the noise level would be very high as @dgubitosi pointed.

**Comment by frederic-mahe** [comment]
The newly added support for zip files might make it more complicated to delete matching files from the source folder. If the matching file is in a zip archive, eliminating the entry would require to update the zip file.

I hope the workaround above will help you identify and list non-matching files.
